name: CI

on:
  push:
    branches:
      - "master"
  pull_request:

env:
  GOLANGCILINT_VERSION: "1.51.1"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20.1"
      - uses: actions/checkout@v3
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v${{ env.GOLANGCILINT_VERSION }}

  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goarch: amd64
            test_target: test-race
          # build and test on 32 bit, does not support race
          - os: ubuntu-latest
            goarch: "386"
            test_target: test
          - os: macos-latest
            goarch: amd64
            test_target: test
          - os: windows-latest
            goarch: amd64
            test_target: test
    runs-on: ${{ matrix.os }}
    steps:
      # only run cli binary tests on linux
      - name: Install expect
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get install expect
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20.1"
      - name: Test
        env:
          GOARCH: ${{ matrix.goarch }}
        run: make ${{ matrix.test_target }}
